---
# right now there are only 2 settings
owner: Example
currency: USD
locale: en_US
theme: auto
autofill_price_mark: Random1~  # existing setting with non-existant value

# non-existant settings don't crash the script
non-existant-setting: Whatever
__getattr__: "In case you try being smart"
