---
name: Generate Report
on:
  schedule:
    - cron: '00 9 * * *'  # generate report everyday at 9:00 UTC
  push:
  workflow_dispatch:

jobs:
  generate-report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout Upstream Repo
        uses: actions/checkout@v5
        with:
          repository: zukaitis/investment-tracker
          ref: ci-rework  # TODO: change to release branch once it's ready
          path: upstream
      - name: Install Python packages
        run: pip3 install -r ./upstream/requirements.txt
      - name: Set input file directory
        id: set_input_dir  # TODO: rename input_data to examples, remove EXAMPLE_ from example file names
        run: |
          if [ -f "*.yaml" ]; then
            echo "input_dir=." >> $GITHUB_OUTPUT
          else
            echo "input_dir=./input_data" >> $GITHUB_OUTPUT
          fi
      - name: Generate Report
        run: ./upstream/generate_report.py --input_dir ${{ steps.set_input_dir.outputs.input_dir }}
      - name: Get Date
        id: get_date
        run: echo "date=$(date -I)" >> $GITHUB_OUTPUT
      - name: Get Datetime
        id: get_datetime
        run: echo "datetime=$(date '+%F %T')" >> $GITHUB_OUTPUT
      - name: Get Tag
        id: get_tag
        run: echo "tag=$(date '+%FT%H%M%S')" >> $GITHUB_OUTPUT
      - name: Get Report Filename
        id: get_report_filename
        run: echo "filename=Report_${{ steps.get_date.outputs.date }}.html" >> $GITHUB_OUTPUT
      - name: Rename Report
        run: mv ./report.html ${{ steps.get_report_filename.outputs.filename }}
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
            keep_latest: 6  # specify how many old releases you want to keep here
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Report ${{ steps.get_datetime.outputs.datetime }}
          draft: false
          prerelease: false
          files: ${{ steps.get_report_filename.outputs.filename }}
