---
name: Generate Report
on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install Python packages
        run: pip3 install pandas numpy plotly yfinance babel dominate dataclasses
      - name: Generate Report
        run: ./generate_report.py
      - name: Get Date
        id: get_date
        run: echo "::set-output name=date::$(date -I)" && echo "::set-output name=datetime::$(date '+%F %T')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Report ${{ steps.get_date.outputs.datetime }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./report.html
          asset_name: Report_${{ steps.get_date.outputs.date }}.html
          asset_content_type: text/html
